{"file_name": "docs/trouble/index.md", "questions": ["What is the solution to address already in use error when running Tracardi?", "How to remap the port Tracardi is running?", "How to change the port mapping from 8686:80 to some other port?", "What is the default docker run command for Tracardi GUI?"], "answer": "# Troubleshooting\nKnown issues that may come up while running Tracardi.\n\n## Address already in use\n\nIf you experience:\n\n```\nERROR: for tracardi_tracardi_1  Cannot start service \ntracardi: driver failed programming external connectivity \non endpoint tracardi_tracardi_1 \nError starting userland proxy: listen tcp4 0.0.0.0:8686: \nbind: address already in use\n``` \n\nThat means you have something running on port 8686. It may be another copy of Tracardi or other service.\n\nThe solution to this is to remap the port Tracardi is running. If you run Tracardi API like this change the port mapping\nfrom `8686:80` to some other port `8888:80`.\n\nChange:\n\n```\ndocker run -p 8686:80 -e ELASTIC_HOST=http://<your-laptop-ip>:9200 tracardi/tracardi-api\n```\n\nTo:\n\n```\ndocker run -p 8888:80 -e ELASTIC_HOST=http://<your-laptop-ip>:9200 tracardi/tracardi-api\n```\n\nRemember that when you change API port then you have it included in GUI as GUI uses API to access data.\n\nSo tak a look at lunch command for GUI:\n\nSo change default docker run command for Tracardi GUI\n\n```\ndocker run -p 8787:80 -e API_URL=//127.0.0.1:8686 tracardi/tracardi-gui\n```\n\nTo (notice: API_URL=//127.0.0.1:8888, this the where the Tracardi API is running)\n\n```\ndocker run -p 8787:80 -e API_URL=//127.0.0.1:8888 tracardi/tracardi-gui\n```\n\n## Installation errors\n\n```\nIndex index `INDEX_NAME` was NOT CREATED. The following result was returned {'error': \n{'root_cause': [{'type': 'validation_exception', 'reason': 'Validation Failed: 1: this action would add [10] shards, \nbut this cluster currently has [1000]/[1000] maximum normal shards open;'}], 'type': 'validation_exception', 'reason': \n'Validation Failed: 1: this action would add [10] shards, but this cluster currently has [1000]/[1000] maximum normal \nshards open;'}, 'status': 400} [Exception]\n```\n\nThis error can pop up if you have your elasticsearch full of indices. This means there are no shards open for new indices.\nRemove unused indices. This error is usually shown during Tracardi update. \n\n## Connecting to Elasticsearch\n\n```\naiohttp.client_exceptions.ClientConnectorError: Cannot connect to host elasticsearch:9200 ssl:default [Connection refused]\n```\n\nThis information may come up if elasticsearch is not running. When elasticsearch starts Tracardi will resume\nautomatically. This information is usually displayed when Tracardi starts before elastic is ready. Tracardi waits for\nelastic to start and checks if it's ready every 5 seconds.\n\nThe above error log may look like this:\n\n```\nINFO:     Started server process [10864]\nINFO:uvicorn.error:Started server process [10864]\nINFO:     Waiting for application startup.\nINFO:uvicorn.error:Waiting for application startup.\n```\n\nThis means Tracardi is waiting for Elastic to start. You will see TimeOut messages if Tracardi could not connect to\nElastic long enough.\n\n### Elastic at localhost error\n\nWhen you run Tracardi API like this:\n\n```\ndocker run -p 8686:80 -e ELASTIC_HOST=http://localhost:9200 tracardi/tracardi-api\n```\n\nNotice that you try to connect to Elastic on localhost. When you run it like this means that you're connecting to the\ndocker itself as localhost means local in docker. Obviously elastic is not there, so Tracardi will never connect. Pass\nexternal ip for elastic. This may be your laptop IP if you are running Tracardi locally.\n\n## Failed to index document\n\nDocument will fail to index if its schema is conflicting with other documents in Tracardi. It this happens you may see\nthis message:\n\n```\nCould not save event. Error: 1 document(s) failed to index. - failed to parse field [properties.id] of type [float] \nin document with id '052df0ed-e719-457c-9de1-3b197c44b44e'. Preview of field's value: 'consent-type'\"\n```\n\nWhy this happens and how to solve it. It happens when the type of data that is already in Tracardi is conflicting with\ndata that's being sent to be saved.\n\nFor example. Consider to following scenario. You have saved age as an integer number for example: 34, 25, 15, 67. It is\nsaved in"}